# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import library_pb2 as library__pb2


class FloorDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFloorData = channel.unary_unary(
                '/FloorDataService/GetFloorData',
                request_serializer=library__pb2.FloorDataRequest.SerializeToString,
                response_deserializer=library__pb2.FloorDataResponse.FromString,
                )


class FloorDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFloorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FloorDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFloorData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFloorData,
                    request_deserializer=library__pb2.FloorDataRequest.FromString,
                    response_serializer=library__pb2.FloorDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FloorDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FloorDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFloorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FloorDataService/GetFloorData',
            library__pb2.FloorDataRequest.SerializeToString,
            library__pb2.FloorDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DeskDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeskData = channel.unary_unary(
                '/DeskDataService/GetDeskData',
                request_serializer=library__pb2.DeskDataRequest.SerializeToString,
                response_deserializer=library__pb2.DeskDataResponse.FromString,
                )


class DeskDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDeskData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeskDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeskData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeskData,
                    request_deserializer=library__pb2.DeskDataRequest.FromString,
                    response_serializer=library__pb2.DeskDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeskDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeskDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDeskData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeskDataService/GetDeskData',
            library__pb2.DeskDataRequest.SerializeToString,
            library__pb2.DeskDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
