# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\",\n\x05\x43hair\x12\x0f\n\x07\x63hairId\x18\x01 \x01(\t\x12\x12\n\nisOccupied\x18\x02 \x01(\x08\"-\n\x04\x44\x65sk\x12\r\n\x05TOPIC\x18\x01 \x01(\t\x12\x16\n\x06VALUES\x18\x02 \x03(\x0b\x32\x06.Chair\"!\n\x07Library\x12\x16\n\x06\x66loors\x18\x01 \x03(\x0b\x32\x06.Floor\".\n\x05\x46loor\x12\x0f\n\x07\x66loorId\x18\x01 \x01(\t\x12\x14\n\x05\x64\x65sks\x18\x02 \x03(\x0b\x32\x05.Desk\"#\n\x10\x46loorDataRequest\x12\x0f\n\x07\x66loorId\x18\x01 \x01(\t\"+\n\x11\x46loorDataResponse\x12\x16\n\x06\x66loors\x18\x01 \x01(\x0b\x32\x06.Floor\" \n\x0f\x44\x65skDataRequest\x12\r\n\x05query\x18\x01 \x01(\t\"(\n\x10\x44\x65skDataResponse\x12\x14\n\x05\x64\x65sks\x18\x01 \x01(\x0b\x32\x05.Desk2K\n\x10\x46loorDataService\x12\x37\n\x0cGetFloorData\x12\x11.FloorDataRequest\x1a\x12.FloorDataResponse\"\x00\x32G\n\x0f\x44\x65skDataService\x12\x34\n\x0bGetDeskData\x12\x10.DeskDataRequest\x1a\x11.DeskDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CHAIR']._serialized_start=17
  _globals['_CHAIR']._serialized_end=61
  _globals['_DESK']._serialized_start=63
  _globals['_DESK']._serialized_end=108
  _globals['_LIBRARY']._serialized_start=110
  _globals['_LIBRARY']._serialized_end=143
  _globals['_FLOOR']._serialized_start=145
  _globals['_FLOOR']._serialized_end=191
  _globals['_FLOORDATAREQUEST']._serialized_start=193
  _globals['_FLOORDATAREQUEST']._serialized_end=228
  _globals['_FLOORDATARESPONSE']._serialized_start=230
  _globals['_FLOORDATARESPONSE']._serialized_end=273
  _globals['_DESKDATAREQUEST']._serialized_start=275
  _globals['_DESKDATAREQUEST']._serialized_end=307
  _globals['_DESKDATARESPONSE']._serialized_start=309
  _globals['_DESKDATARESPONSE']._serialized_end=349
  _globals['_FLOORDATASERVICE']._serialized_start=351
  _globals['_FLOORDATASERVICE']._serialized_end=426
  _globals['_DESKDATASERVICE']._serialized_start=428
  _globals['_DESKDATASERVICE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
